### ISSUE TITLE
Number of decimal places for alpha and beta in plot curve function

### ISSUE THREAD

**Issue by vmsatya** [bhklab/RadioGx#12]
plotCurve(c(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10), c(1.1, 0.8, 0.7, 0.45, 0.15, -0.1, -0.1, -0.4, -0.65, -0.75, -1.1))
[1] "A linear-quadratic curve was fit to the data with parameters alpha = 0 and beta = 0.00946875000000001."

Might be good to trim the number roof decimal places to 4 for both parameters

**Comment by vmsatya** [comment]
Will you be truncating to 5 decimal places, instead of 17 in the current version

**Comment by p-smirnov** [comment]
Fixed to 2 decimal places in legend in: 
c6767c73192f0c6817f999dd4facf40078f6da34
