### ISSUE TITLE
Different AUC values for the same points 

### ISSUE THREAD

**Issue by vmsatya** [bhklab/RadioGx#17]
Dose points 9 and 10 are swapped
computeAUC(c(0, 1, 2, 3, 4, 5, 6, 7, 8, 10, 9), c(1.1, 0.8, 0.7, 0.45, 0.15, -0.1, -0.1, -0.4, -0.65, -1.1, -0.75))
-2.552083
computeAUC(c(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10), c(1.1, 0.8, 0.7, 0.45, 0.15, -0.1, -0.1, -0.4, -0.65, -0.75, -1.1))
-3.15625

################################

The ordering of dose points is taken care of in the LQmodel fit but not in computeAUC function

**Comment by p-smirnov** [comment]
I think this is fixed

**Comment by vmsatya** [comment]
This function should not take negative values as we are disabling the log to the user. Input should be in fraction of cells only

**Comment by p-smirnov** [comment]
Yes, also fixed in latest commits to CoreGx

**Comment by p-smirnov** [comment]
It simply removes negatives with a warning
