### ISSUE TITLE
compiteAUC gives zero

### ISSUE THREAD

**Issue by vmsatya** [bhklab/RadioGx#19]
computeAUC(c(0, 1, 2, 3, 4), c(10, 20, 30, 40,50))

value is 0

**Comment by p-smirnov** [comment]
I think this is fixed

**Comment by vmsatya** [comment]
Can you disable the log option in this function as well ? 
computeAUC(c(0, 1, 2, 3, 4), c(10, 20, 30, 40,50))
[1] -6.4

computeAUC(c(0, 1, 2, 3, 4), c(10, 20, 30, 40,50),SF_as_log=FALSE)
[1] 1.614873
