### ISSUE TITLE
Theoretical Linear Quadratic fit returns zero values for parameters

### ISSUE THREAD

**Issue by vmsatya** [bhklab/RadioGx#2]
linearQuadraticModel(c(0,1,2,3,4,5,6,7,8,9,10),c(1.0000000,0.8958341,0.7866279,0.6770569,0.5712091,0.4723666,0.3828929,0.3042213,0.2369278,0.1808658,0.1353353),SF_as_log=FALSE)

For the above values: alpha = 0.1 per gray and beta  = 0.01 per (gray*gray)

**Comment by p-smirnov** [comment]
Fixed by fixing base of the fitting function
