### ISSUE TITLE
Not performing the sanity check for fraction of SF cells being negative and SF_as_log parameter in the function

### ISSUE THREAD

**Issue by vmsatya** [bhklab/RadioGx#3]
linearQuadraticModel(c(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10), c(1.1, 0.8, 0.7, 0.45, 0.15, -0.1, -0.1, -0.4, -0.65, -0.75, -1.1),SF_as_log=FALSE)

 linearQuadraticModel(c(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10), c(1.1, 0.8, 0.7, 0.45, 0.15, -0.1, -0.1, -0.4, -0.65, -0.75, -1.1),SF_as_log=TRUE)

returns: alpha = 0 and beta = 0.00946875

**Comment by p-smirnov** [comment]
No more sf log parameters
