### ISSUE TITLE
Error in the optimization function

### ISSUE THREAD

**Issue by vmsatya** [bhklab/RadioGx#33]
Below is the synthetic data:
linearQuadraticModel(c(0,1,2,3),c(1.1, 0.2, 0.7, 0.1),SF_as_log=FALSE,family="normal")
$alpha
[1] 0.3
$beta
[1] 0.1322388

If the optimization is correct, changing the parameter bounds should not change the parameter values
linearQuadraticModel(c(0,1,2,3),c(1.1, 0.2, 0.7, 0.1),SF_as_log=FALSE,family="normal",lower_bounds = c(-0.4, -0.4),upper_bounds = c(0.5, 0.5))
$alpha
[1] 0.6489688
$beta
[1] 0.00403125

**Comment by p-smirnov** [comment]
Cannot reproduce on my machine right now, maybe my latest updates will fix.

**Comment by vmsatya** [comment]
How stable is the optimization function with respect to the number of points used for the fit?
