### ISSUE TITLE
Round3: Wrong AUC values

### ISSUE THREAD

**Issue by vmsatya** [bhklab/RadioGx#44]
How does the function take care of there are negative values ? Why is it we get the same AUC value --- are you choosing the absolute value of the SF ? 
computeAUC(c(0, 2, 3, 4), c(10, 20, 30, 40))  = 0.8862269
computeAUC(c(0, 2, 3, 4), c(10, 20, 30, -40)) = 0.8862269
computeAUC(c(0, 2, 3, 4), c(10, 20, -30, -40)) = 0.8862269
computeAUC(c(0, 2, 3, 4), c(10, -20, -30, -40)) 
Error in if (test_guess_residual < guess_residual) { : 
  missing value where TRUE/FALSE needed

**Comment by p-smirnov** [comment]
I am not sure what the right behaviour here is, it integrates from 0 to 4 regardless of whether the values are used in curve fitting.

**Comment by vmsatya** [comment]
When you are integrating, are you considering -40 or 40 ?

**Comment by p-smirnov** [comment]
Neither, it is dropped unless you use area.type="Actual"

**Comment by vmsatya** [comment]
Thanks, I was indeed concerned with the Actual area type only

**Comment by vmsatya** [comment]
Warning message when truncating to 0 and 1
