### ISSUE TITLE
Critical Bug: Different results using computeAUC and LQmodel functions

### ISSUE THREAD

**Issue by vmsatya** [bhklab/RadioGx#55]
Although few cell lines have non zero alpha and beta values obtained form the LQ model, however, when we compute the AUC, we get zero. Please check the excel file for the results. 

[TestValues.xlsx](https://github.com/bhklab/RadioGx/files/1318063/TestValues.xlsx)

**Comment by p-smirnov** [comment]
This is a numerical precision error

**Comment by p-smirnov** [comment]
I am trying to fix

**Comment by p-smirnov** [comment]
Code was updated to use numeric approximation of integral, works on test cases now. @vmsatya please check?
