### ISSUE TITLE
Radiogx Installation issue 

### ISSUE THREAD

**Issue by vmsatya** [bhklab/RadioGx#56]
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
*** arch - i386
Warning: no function found corresponding to methods exports from 'RadioGx' for: 'radiationNames', 'radiationNames<-'
Error: package or namespace load failed for 'RadioGx' in loadNamespace(package, lib.loc):
 in 'RadioGx' methods for export not found: radiationNames, radiationNames<-
Error: loading failed
Execution halted
*** arch - x64
Warning: no function found corresponding to methods exports from 'RadioGx' for: 'radiationNames', 'radiationNames<-'
Error: package or namespace load failed for 'RadioGx' in loadNamespace(package, lib.loc):
 in 'RadioGx' methods for export not found: radiationNames, radiationNames<-
Error: loading failed
Execution halted
ERROR: loading failed for 'i386', 'x64'
* removing 'C:/Users/Satya/Documents/R/win-library/3.4/RadioGx'
Installation failed: Command failed (1)

**Comment by LeahBriscoe** [comment]
I also encountered this problem. I deleted the 4 lines in the NAMESPACE file containing the words radiationNames, and the installation worked thereafter.
