### ISSUE TITLE
Error message for single response with multiple dose points

### ISSUE THREAD

**Issue by vmsatya** [bhklab/RadioGx#6]
linearQuadraticModel(c(1,2,3,4,5),c(1.0000000,1.0000000,1.0000000,1.0000000,1.0000000))
$alpha
[1] 0

$beta
[1] 0

**Comment by p-smirnov** [comment]
Should I warn the user or leave as is? technically there could be no observed effect at all.

**Comment by vmsatya** [comment]
I think it is fine, as we only get a straight line without any slope. We will leave it to the user.
