### ISSUE TITLE
Issue with Verbose option in the LQmodel fit

### ISSUE THREAD

**Issue by vmsatya** [bhklab/RadioGx#8]
linearQuadraticModel(c(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10), c(1.1, 0.8, 0.7, 0.45, 0.15, -0.1, -0.1, -0.4, -0.65, -0.75, -1.1),verbose=TRUE)
$alpha
[1] 0

$beta
[1] 0.00946875

Warning messages:
1: In CoreGx:::.sanitizeInput(x = D, y = SF, x_as_log = FALSE, y_as_log = SF_as_log,  :
  Warning: Negative y data.
2: In CoreGx:::.sanitizeInput(x = D, y = SF, x_as_log = FALSE, y_as_log = SF_as_log,  :
  Warning: y data exceeds negative control.

**Comment by p-smirnov** [comment]
Both warning messages are correct, there are survival fractions > 1 and < 0.
